name: Deploy Java Bot

on:
  push:
    paths:
      - 'java-bot/**'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
      - name: Build
        run: cd java-bot && mvn package
      - name: Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
